simplify usage of save_y2logs (bnc#673990)
svn path=/trunk/yast2/; revision=66036

diff --git a/scripts/save_y2logs b/scripts/save_y2logs
--- a/scripts/save_y2logs
+++ b/scripts/save_y2logs
@@ -7,15 +7,18 @@
 
 usage()
 {
-    echo "Usage: $0 <tgz-file-name>|<bzip2-file-name>" >&2
+    echo "Usage: $0 [<tgz-file-name>|<bzip2-file-name>]" >&2
     echo "" >&2
     echo "Copies the YaST2 logs to a compressed tar archive." >&2
+    echo "If file name is missing, it is generated by the script." >&2
     exit 1
 }
 
-test -z "$1" && usage
-
-case "$1" in
+if test -z "$1"; then
+  TARGET=`mktemp --suffix .tar.gz /tmp/y2log-XXXXXX`
+  COMPRESSION=--gzip
+else
+  case "$1" in
     -*)
 	usage
 	;;
@@ -40,7 +43,8 @@ case "$1" in
 	echo "FATAL: Uncompressed archives not supported" >&2
 	echo "Use one of: .tgz .tar.gz .tar.bz2"          >&2
 	exit 4
-esac
+  esac
+fi
 
 TMPDIR=`mktemp -d` || ( echo "FATAL: Failed to create a temporary directory" >&2; exit 5 );
 LIST=YaST2
