remove all passwords from install.inf in save_y2log (bnc#500130)
svn path=/trunk/yast2/; revision=57068

diff --git a/scripts/save_y2logs b/scripts/save_y2logs
--- a/scripts/save_y2logs
+++ b/scripts/save_y2logs
@@ -42,7 +42,7 @@ case "$1" in
 	exit 4
 esac
 
-
+TMPDIR=`mktemp -d` || ( echo "FATAL: Failed to create a temporary directory"; exit 5 );
 LIST=YaST2
 
 if [ -f /var/log/evms-engine.log ]; then
@@ -54,7 +54,8 @@ if [ -f /var/log/zypp/history ]; then
 fi
 
 if [ -f /etc/install.inf ]; then
-    LIST="$LIST /etc/install.inf"
+    sed 's/\(^WlanESSID: \|^WlanKey: \|^RootPassword: \|^VNCPassword: \|^Password: \).*$/\1XXXXXX/' </etc/install.inf >$TMPDIR/install.inf
+    LIST="$LIST $TMPDIR/install.inf"
 fi
 
 if [ -f /etc/X11/xorg.conf ]; then
@@ -84,7 +85,7 @@ fi
 
 echo "Saving y2logs to $TARGET"
 
-tar cf "$TARGET" $COMPRESSION --directory=/var/log $LIST && exit 0
+tar cf "$TARGET" $COMPRESSION --directory=/var/log $LIST && rm -rf $TMPDIR && exit 0
 
 echo "FATAL: Error creating archive $TARGET" >&2
 exit 2
