updated start-up script to behave correctly if QT CC is to be used without QT back-end (bnc#545331)
svn path=/trunk/yast2/; revision=60263

diff --git a/scripts/yast2 b/scripts/yast2
--- a/scripts/yast2
+++ b/scripts/yast2
@@ -183,16 +183,25 @@ select_gui_frontend()
 	if check_gtk; then
 	    SELECTED_GUI=gtk
 	else
-	    echo >&2 "GTK GUI wanted but not found, falling back to Qt."
-	    WANTED_GUI=qt
+	    if check_qt; then
+		SELECTED_GUI=qt
+		WANTED_GUI=qt
+		echo >&2 "GTK GUI wanted but not found, falling back to Qt."
+	    else
+		echo >&2 "GTK GUI wanted but not found, falling back to ncurses."
+	    fi
 	fi
-    fi
-
-    if [ "$WANTED_GUI" = "qt" ]; then
+    elif [ "$WANTED_GUI" = "qt" ]; then
 	if check_qt; then
 	    SELECTED_GUI=qt
 	else
-	    echo >&2 "Qt GUI wanted but not found, falling back to ncurses."
+	    if check_gtk; then
+		SELECTED_GUI=gtk
+		WANTED_GUI=gtk
+		echo >&2 "Qt GUI wanted but not found, falling back to GTK."
+	    else
+		echo >&2 "Qt GUI wanted but not found, falling back to ncurses."
+	    fi
 	fi
     elif [ "$SELECTED_GUI" != "gtk" -a "$WANTED_GUI" != "ncurses" ]; then
 	echo >&2 "Unknown GUI '$WANTED_GUI', falling back to ncurses."
