remove support for the GTK frontend which is scheduled for removal

diff --git a/scripts/yast2 b/scripts/yast2
--- a/scripts/yast2
+++ b/scripts/yast2
@@ -19,7 +19,7 @@ export PATH=/sbin:/usr/sbin:$PATH
 unset GEM_HOME GEM_PATH RUBYLIB RUBYPATH RUBYOPT
 
 # we need input methods for many locales bnc#776567
-export QT_IM_MODULE=xim GTK_IM_MODULE=xim
+export QT_IM_MODULE=xim
 
 # Do not load libproxy modules (config_kde4 module crashes because of Qt4/Qt5
 # clash), empty path causes that the installed modules are not found. Sysconfig
@@ -58,7 +58,7 @@ exit_code=0
 # Accumulated arguments for both the Qt UI and y2cc; currently supported:
 # --fullscreen
 # --noborder
-# well also for gtk and ncurses
+# well also for ncurses
 Y2UI_ARGS=""
 GNOME_SHELL="$ybindir/y2controlcenter-gnome"
 KDE_SHELL="$ybindir/y2controlcenter"
@@ -71,7 +71,6 @@ printhelp()
 	echo "	-h, --help	this message"
 	echo "	-l, --list	list all available modules"
 	echo "	--qt            use the QT graphical user interface"
-	echo "	--gtk           use the GTK graphical user interface"
 	echo "	--ncurses       use the NCURSES text-mode user interface"
 	echo "	-g, --geometry	default window size (qt only)"
 	echo "	--noborder      no window manager border for main window"
@@ -94,85 +93,33 @@ listmodules()
     fi
 }
 
-# Probes for default desktop GUI
-probe_desktop_gui()
-{
-    if [ "$DESKTOP_SESSION" = "gnome" -o \
-         "$DESKTOP_SESSION" = "LXDE" -o \
-         "$DESKTOP_SESSION" = "xfce" ]; then
-	DESKTOP_GUI="gtk"
-    elif echo $WINDOWMANAGER | grep -qi "\(gnome\|xfce|lxde\)"; then
-	DESKTOP_GUI="gtk"
-    else
-	DESKTOP_GUI="qt"
-    fi
-    if [ "$DESKTOP_GUI" = "qt" -a ! -x "$KDE_SHELL" ]; then
-	DESKTOP_GUI="gtk"
-    fi
-    if [ "$DESKTOP_GUI" = "gtk" -a ! -x "$GNOME_SHELL" ]; then
-	DESKTOP_GUI="qt"
-    fi
-}
-
 # Select which control center shell we want to use
 select_control_center()
 {
     # 'auto' detects desktop
     if [ "$WANTED_SHELL" = "auto" ]; then
-	probe_desktop_gui
 	WANTED_SHELL=$DESKTOP_GUI
     fi
 
     # select binary
-    y2ccbin=""
-    case "$WANTED_SHELL" in
-	gtk)
-	    y2ccbin="$GNOME_SHELL"
-	    ;;
-	*)
-	    y2ccbin="$KDE_SHELL"
-	    ;;
-    esac
+    y2ccbin="$KDE_SHELL"
 }
 
 # Select which toolkit we want to use (F#301083)
 select_gui_frontend()
 {
     if [ "$WANTED_GUI" = "auto" ]; then
-	probe_desktop_gui
 	WANTED_GUI=$DESKTOP_GUI
 	GUI_SELECTION=auto
     fi
 
-    if [ "$WANTED_GUI" = "gtk" ]; then
-	if check_gtk; then
-	    SELECTED_GUI=gtk
-	else
-	    if check_qt; then
-		SELECTED_GUI=qt
-		WANTED_GUI=qt
-		if [ "$GUI_SELECTION" != "auto" ]; then
-		    echo >&2 "GTK GUI wanted but not found, falling back to Qt."
-		fi
-	    else
-		echo >&2 "GTK GUI wanted but not found, falling back to ncurses."
-	    fi
-	fi
-    elif [ "$WANTED_GUI" = "qt" ]; then
+    if [ "$WANTED_GUI" = "qt" ]; then
 	if check_qt; then
 	    SELECTED_GUI=qt
 	else
-	    if check_gtk; then
-		SELECTED_GUI=gtk
-		WANTED_GUI=gtk
-		if [ "$GUI_SELECTION" != "auto" ]; then
-		    echo >&2 "Qt GUI wanted but not found, falling back to GTK."
-		fi
-	    else
-		echo >&2 "Qt GUI wanted but not found, falling back to ncurses."
-	    fi
+            echo >&2 "Qt GUI wanted but not found, falling back to ncurses."
 	fi
-    elif [ "$SELECTED_GUI" != "gtk" -a "$WANTED_GUI" != "ncurses" ]; then
+    elif [ "$WANTED_GUI" != "ncurses" ]; then
 	echo >&2 "Unknown GUI '$WANTED_GUI', falling back to ncurses."
     fi
 }
@@ -234,7 +181,7 @@ other_tools_are_conflicting ()
   return 0
 }
 
-TEMP=`/usr/bin/getopt -o hlg:s:Si --long help,list,kcontrol,geometry:,style:,strings,install,update,remove,fullscreen,noborder,qt,gtk,ncurses \
+TEMP=`/usr/bin/getopt -o hlg:s:Si --long help,list,kcontrol,geometry:,style:,strings,install,update,remove,fullscreen,noborder,qt,ncurses \
      -n 'yast2' -- "$@"`
 
 if [ $? != 0 ] ; then echo "Exit." >&2 ; exit 1 ; fi
@@ -254,7 +201,6 @@ while true ; do
 		--noborder)   Y2UI_ARGS="$Y2UI_ARGS --noborder"  ; shift ;;
 		--kcontrol)   Y2UI_ARGS="$Y2UI_ARGS --kcontrol_id YaST" ; shift ;;
 		--qt)  export CMDLINE_UI="qt"  ; shift ;;
-		--gtk)  export CMDLINE_UI="gtk"  ; shift ;;
 		--ncurses)  unset DISPLAY ; shift ;;
 		--) shift ; break ;;
 		*) echo "Unrecognized option $1" ; exit 1 ;;
@@ -382,20 +328,17 @@ if [ "$SELECTED_GUI" = "ncurses" ]; then
 	fi
 
     else
-	rpm -V yast2-core yast2-ncurses yast2-qt yast2-gtk >&2
+	rpm -V yast2-core yast2-ncurses yast2-qt >&2
 	echo "Something is wrong with the YaST user interface." >&2
 	exit_code=1		# also skips y2base later
     fi
     if [ -n "$DISPLAY" -a ! -t 0 ]; then
-	rpm -V yast2-core yast2-ncurses yast2-qt yast2-gtk >&2
+	rpm -V yast2-core yast2-ncurses yast2-qt >&2
 	echo "Something is wrong with the YaST user interface, NCurses selected but no terminal available." >&2
 	exit_code=1		# also skips y2base later
     fi
-elif [ "$SELECTED_GUI" = "qt" -o "$SELECTED_GUI" = "gtk" ]; then
-
-    if [ "$SELECTED_GUI" = "qt" ]; then
-	set_qt_home_dir
-    fi
+elif [ "$SELECTED_GUI" = "qt" ]; then
+    set_qt_home_dir
 
     # find which control center shell we want, if there is none we
     # fall back to the built-in ycp menu
