Error is reported if user explicitely wanted the GUI he hasn't got

diff --git a/scripts/yast2 b/scripts/yast2
--- a/scripts/yast2
+++ b/scripts/yast2
@@ -135,6 +135,7 @@ select_gui_frontend()
     if [ "$WANTED_GUI" = "auto" ]; then
 	probe_desktop_gui
 	WANTED_GUI=$DESKTOP_GUI
+	GUI_SELECTION=auto
     fi
 
     if [ "$WANTED_GUI" = "gtk" ]; then
@@ -144,6 +145,9 @@ select_gui_frontend()
 	    if check_qt; then
 		SELECTED_GUI=qt
 		WANTED_GUI=qt
+		if [ "$GUI_SELECTION" != "auto" ]; then
+		    echo >&2 "GTK GUI wanted but not found, falling back to Qt."
+		fi
 	    else
 		echo >&2 "GTK GUI wanted but not found, falling back to ncurses."
 	    fi
@@ -155,6 +159,9 @@ select_gui_frontend()
 	    if check_gtk; then
 		SELECTED_GUI=gtk
 		WANTED_GUI=gtk
+		if [ "$GUI_SELECTION" != "auto" ]; then
+		    echo >&2 "Qt GUI wanted but not found, falling back to GTK."
+		fi
 	    else
 		echo >&2 "Qt GUI wanted but not found, falling back to ncurses."
 	    fi
